language: python
python:
  - 3.8

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.26.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d

before_script:
  - docker-compose ps 
  - docker exec -it maple_boss_logger_db bash psql -c 'CREATE DATABASE maple_boss_logger' -U postgres
  - psql -c 'CREATE DATABASE maple_boss_logger' -U postgres
  - psql -c 'CREATE USER django WITH PASSWORD "password"' -U postgres
  - psql -c 'ALTER ROLE django SET client_encoding TO "utf8"' -U postgres
  - psql -c 'ALTER ROLE django SET default_transaction_isolation TO "read committed"' -U postgres
  - psql -c 'ALTER ROLE django SET timezone TO "Asia/Tokyo"' -U postgres
  - psql -c 'ALTER USER django CREATEDB' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE maple_boss_logger TO django' -U postgres


script:
  - docker-compose run web python manage.py test