version: '3'
services:
 web:
   container_name: maple_boss_logger
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 18000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
   container_name: maple_boss_logger_db
   image: postgres:latest
   restart: always
   environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: root
       POSTGRES_PASSWORD: password
       POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
   volumes:
     - ./postgres_data:/var/lib/postgresql/data
   ports:
     - 33306:3306