version: '3'
services:
 web:
   container_name: maple_boss_logger
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 18000:8000
   volumes:
     - .:/code
