# Generated by Django 3.0.8 on 2020-08-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_id', models.CharField(max_length=3, unique=True)),
                ('boss_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserBossHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=3)),
                ('last_challenged_date', models.DateTimeField(verbose_name='date challenged')),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logger.Boss', to_field='boss_id')),
            ],
        ),
    ]
