# Generated by Django 3.1 on 2020-08-12 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20200812_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='boss_limit_type',
            field=models.CharField(choices=[('UN', 'Unknown'), ('DA', 'Daily'), ('WE', 'Weekly')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='boss',
            name='boss_reward_meso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbosshistory',
            name='challenged_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date challenged'),
        ),
    ]
