name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: upgrade pipenv and Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test logger